Hw06 email
Tarasdeveloper/nodejs-homework-rest-api pull request #5
Opened 2023-09-29 19:46 UTC by Tarasdeveloper

2023-09-30 08:57 UTC, ceREAL133 requested changes

2023-09-30 08:57 UTC, ceREAL133 commented on controllers/auth-controller.js
> +    verificationToken: 'Verified',
тут токен має мінятись на null. Поміняйте і протестуйте

2023-09-30 09:01 UTC, Tarasdeveloper commented on controllers/auth-controller.js
> +    verificationToken: 'Verified',
Не меняется на null, по другому не работает

2023-09-30 09:06 UTC, Tarasdeveloper commented on controllers/auth-controller.js
> +    verificationToken: 'Verified',
message | "Validation failed: verificationToken: Verify token is required"

2023-09-30 09:11 UTC, Tarasdeveloper commented on controllers/auth-controller.js
> +    verificationToken: 'Verified',
Поменял на 'null'

2023-09-30 16:59 UTC, ceREAL133 requested changes

2023-09-30 16:59 UTC, ceREAL133 commented on controllers/auth-controller.js
> +    verificationToken: 'null',
має бути конкретно null

2023-09-30 16:59 UTC, ceREAL133 commented on models/User.js
на 48й строці є userSchema.pre('findOneAndUpdate', runValidateAtUpdate);, це є причиною, чому null не пропускає

2023-09-30 17:28 UTC, Tarasdeveloper commented on models/User.js
И что же с этой строкой делать?

2023-10-01 05:25 UTC, ceREAL133 approved these changes

2023-10-01 10:05 UTC, merged